### ISSUE TITLE
Installation Doc.

### ISSUE THREAD

**Issue by coolternet** [mindplay-dk/lang#1]
Hello. I try to use it but im not able to test.
Fatal error: Uncaught Error: Call to undefined function configure() in E:\UwAmp\www\lang\test.php:7 Stack trace: #0 {main} thrown in E:\UwAmp\www\lang\test.php on line 7

line #7 : configure()->enableCodeCoverage(__DIR__ . '/build/clover.xml', dirname(__DIR__) . '/src');

i dont have /build/clover.xml...

**Comment by mindplay-dk** [comment]
`composer install` then `php test/test.php` should work?

**Comment by mindplay-dk** [comment]
It runs on my local system and on the CI server without problems, so I'm going to assume there's no real problem here.
